<?php include __DIR__ . '/../layout_header.phtml'; ?>

<h1><?php echo isset($contact) ? 'Editar contato' : 'Adicionar contato'; ?></h1>
<hr class="mb-3">

<div class="clearfix">
  <div class="float-right">
    <div class="btn-group mb-3">
      <a href="/" class="btn btn-success">
        <i class="fa fa-long-arrow-left"></i> Voltar para a lista
      </a>
      <?php if (isset($contact)) : ?>
        <a href="/contatos/criar" class="btn btn-primary">
          <i class="fa fa-plus"></i> Adicionar contato
        </a>
      <?php endif; ?>
    </div>
  </div>
</div>

<form action="<?php echo isset($contact) ? '/contatos/atualizar' : '/contatos/armazenar' ; ?>" method="POST">
  <?php if (isset($contact)) : ?>
    <input type="hidden" name="id" value="<?php echo $contact->id; ?>">
  <?php endif; ?>

  <div class="form-group">
    <label for="name">Nome</label>
    <input type="text" id="name" name="name" class="form-control"
      value="<?php echo isset($contact) ? $contact->name : ''; ?>">
  </div>

  <div class="form-group">
    <label for="email">E-mail</label>
    <input type="email" id="email" name="email" class="form-control"
      value="<?php echo isset($contact) ? $contact->email : ''; ?>">
  </div>

  <div class="form-group">
    <label for="website">Site</label>
    <input type="text" id="website" name="website" class="form-control"
      value="<?php echo isset($contact) ? $contact->website : ''; ?>">
  </div>

  <div class="form-group">
    <label for="group">Grupo</label>
      <input list="group" name="group" class="form-control"
        value="<?php echo isset($contact) ? $contact->group : ''; ?>">
      
      <datalist id="group">
        <?php foreach ( $groups as $g) : ?>  
          <option value="<?php echo $g; ?>">
        <?php endforeach; ?>   
      </datalist>

  </div>

  <?php foreach (['Casa', 'Trabalho', 'Celular'] as $label) : ?>
    <div class="form-group">
      <label>Telefone (<?php echo $label; ?>)</label>
      <input type="text" name="phones[<?php echo $label; ?>]" class="form-control"
        value="<?php echo isset($contact) ? $contact->phones[$label] : ''; ?>">
    </div>
  <?php endforeach; ?>

  <button type="submit" class="btn btn-primary">
    <?php echo isset($contact) ? '<i class="fa fa-edit"></i> Editar' : '<i class="fa fa-plus"></i> Adicionar' ; ?> contato
  </button>
</form>

<?php include __DIR__ . '/../layout_footer.phtml'; ?>
