<?php include __DIR__ . '/../layout_header.phtml'; ?>

<h1>Agenda</h1>
<hr class="mb-3">

<div class="clearfix">
  <div class="float-right">
    <div class="btn-group mb-3">
      <a href="/admin" class="btn btn-warning">
        <i class="fa fa-dashboard"></i> Administração
      </a>
      <a href="/contatos/criar" class="btn btn-primary">
        <i class="fa fa-plus"></i> Adicionar contato
      </a>
    </div>
  </div>
</div>

<?php if (empty($contacts)) : ?>
  <p class="lead text-center text-warning">
    <i class="fa fa-warning"></i><br>
    Agenda vazia
  </p>
<?php else : ?>
  <table class="table table-striped table-bordered table-hover">
    <thead class="thead-dark">
      <tr>
        <th>Nome</th>
        <th>Grupo</th>
         <th>Telefones</th>
        <th style="width: 15%">Ações</th>
      </tr>
    </thead>
    <tbody>
      <?php foreach ($contacts as $contact) : ?>
        <tr id="contact_<?php echo $contact->id ?>">
          <td><?php echo $contact->name ?></td>
          <td><?php echo $contact->group ?></td>
           <td>
            <?php if ($contact->phones != '') : ?>
            <?php $phones = json_decode($contact->phones, true); ?>
             <dl class="row">
              <?php foreach ($phones as $label => $phone) : ?>
                <dt class="col-3"><?php echo $label ?>:</dt>
                <dd class="col-9"><?php echo $phone ?></dd>
              <?php endforeach; ?>
             </dl>
            <?php endif; ?>
           </td>
          <td>
            <a href="/contatos/editar?id=<?php echo $contact->id ?>" class="btn btn-sm btn-primary">
              <i class="fa fa-edit"></i>
            </a>
            <a href="/contatos/remover?id=<?php echo $contact->id ?>" class="btn btn-sm btn-danger">
              <i class="fa fa-times"></i>
            </a>
          </td>
        </tr>
      <?php endforeach; ?>
    </tbody>
  </table>
<?php endif; ?>

<?php include __DIR__ . '/../layout_footer.phtml'; ?>
